const http = {
  OK: 'OK', // 200
  CREATED: 'CREATED', // 201
  ACCEPTED: 'ACCEPTED', // 202
  NO_CONTENT: 'NO_CONTENT', // 204
  BAD_REQUEST: 'BAD_REQUEST', // 400
  UNAUTHORIZED: 'UNAUTHORIZED', // 401
  NOT_FOUND: 'NOT_FOUND', // 404
  CONFLICT: 'CONFLICT', // 409
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY', // 422
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', // 500
};

module.exports = http;
